### ISSUE TITLE
Run diamond generation at compile time

### ISSUE THREAD

**Issue by raulk** [consensus-shipyard/ipc-monorepo#10] opened 2023-12-19 12:11 UTC
## Context

Currently we compute selectors and form the diamond at runtime. It happens in two places:

- Integration tests (for testing)
- Deployment scripts (for fresh deployment)

This involves some mildly complicated machinery that happens to be flaky in CI and outside. The machinery consists of:

- Foundry logic (tests and scripts above)...
- ... which calls `TestUtils#generateSelectors`...
- ... which calls `vm.ffi`, which calls...
- the `get_selectors.py` Python script to enumerate function selectors within a given contract.

We then use those selectors to form the diamond at runtime. For example, in integration tests this happens here:

- `IntegrationTestBase#createSubnetActor`
- `IntegrationTestBase#createGatewayDiamond`
- `IntegrationTestBase#createSubnetRegistry`

(I haven't had time to dig into how this work for contract deployment time.)

## Proposal

1. Codegen the selectors and diamond skeleton at compile time.
2. Remove the diamond creation from tests, and use the generated skeleton.
3. Do the same for deployment scripts.
4. Figure out how this simplified approach would interact with the diamond upgrade tooling.

**Comment by snissn** [comment] 2023-12-19 23:04
I think part of the problem is that we're passing in the argument that's just the contract name and that takes much longer than passing the filename in addition:

```
mikers@mikers-B560-DS3H-AC-Y1:~/dev/consensus-shipyard/ipc-solidity-actors$ time forge inspect src/gateway/GatewayManagerFacet.sol:GatewayManagerFacet methodIdentifiers
{
  "addStake()": "5a627dbc",
  "fund((uint64,address[]),(uint8,bytes))": "18f44b70",
  "fundWithToken((uint64,address[]),(uint8,bytes),uint256)": "0517e1aa",
  "kill()": "41c0e1b5",
  "register(uint256)": "f207564e",
  "release((uint8,bytes))": "6b2c1eef",
  "releaseRewardForRelayer(uint256)": "d8e25572",
  "releaseStake(uint256)": "45f54485"
}

real	0m0.357s
user	0m0.499s
sys	0m1.138s
mikers@mikers-B560-DS3H-AC-Y1:~/dev/consensus-shipyard/ipc-solidity-actors$ time forge inspect GatewayManagerFacet methodIdentifiers
{
  "addStake()": "5a627dbc",
  "fund((uint64,address[]),(uint8,bytes))": "18f44b70",
  "fundWithToken((uint64,address[]),(uint8,bytes),uint256)": "0517e1aa",
  "kill()": "41c0e1b5",
  "register(uint256)": "f207564e",
  "release((uint8,bytes))": "6b2c1eef",
  "releaseRewardForRelayer(uint256)": "d8e25572",
  "releaseStake(uint256)": "45f54485"
}

real	0m25.687s
user	0m25.145s
sys	0m0.653s

```
I am creating a script to precompile the selectors and will use the full path in order to speed thing sup

**Comment by snissn** [comment] 2023-12-20 20:26
related to this ticket there is a PR with most of the work here and two follow on issues:
- https://github.com/consensus-shipyard/ipc-solidity-actors/pull/407

- https://github.com/consensus-shipyard/ipc-monorepo/issues/493
- https://github.com/consensus-shipyard/ipc-monorepo/issues/494

**Comment by snissn** [comment] 2024-01-09 20:34
this ticket was intended to be closed with my previous comment. closing with this comment

**Closed by snissn** 2024-01-09 20:34 UTC
Labels: s:ipc-solidity-actors
